const BASE_URL = ''
const MPESA_CONSUMER_KEY = ''   
const MPESA_CONSUMER_SECRET = '' 
const MPESA_PASSKEY = ''
const MPESA_SHORTCODE = ''

export {
    MPESA_CONSUMER_KEY,
    MPESA_CONSUMER_SECRET,
    MPESA_PASSKEY,
    MPESA_SHORTCODE,
    BASE_URL
}